language: java

addons:
  sonarcloud:
    organization: "retest"
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - ${HOME}/.m2/
    - ${HOME}/.sonar/cache/

before_install:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
